### PR TITLE
Use prettier for style

### PR DESCRIPTION
**Pull request by SimenB**
This uses prettier through the eslint plugin to keep the workflow the same.

I removed the conflicting rules from eslintrc, and tried to keep the config they wanted (4 space indent, no semis and 100 char width).

### CODE REVIEW

**Comment by af** [comment]
Thanks for the PR! I'm a bit hesitant to merge it though, IMO prettier makes some sections (eg ternaries and some of the extra linebreaks) a little more difficult to read. I know it's being adopted widely, and I like the fact that it automates code style considerations, so I definitely see the value. Are there some more extra config options for the things I mentioned?

**Comment by SimenB** [comment]
No options for ternaries and extra linebreaks, no.

I know that doing something about ternaries is on the maintainers' list (at least nested ones https://github.com/prettier/prettier/pull/2398#issuecomment-315182247https://github.com/prettier/prettier/pull/2398#issuecomment-315182247).

WRT line breaks, prettier respects if you have extra line breaks in e.g. object literals. If there are any specific changes prettier did that you don't like, we can add a `prettier-ignore` comment above it

**Comment by af** [comment]
Nice, I'll take this for a spin soon and see if prettier can win over this old-school manual formatting curmudgeon ;)

**Comment by kachkaev** [comment]
It'd be great to see prettier in the project! I've been using it for a while and felt so odd while writing https://github.com/af/envalid/pull/55, because the code did not correct itself 😃 

@SimenB could you please rebase this PR if #55 is merged?

**Comment by SimenB** [comment]
Yup, I keep rebasing it after every merge in the hopes of it getting merged 😄

**Comment by af** [comment]
OK, I'm willing to give in on this one :) One more rebase from @SimenB and we can merge

**Comment by SimenB** [comment]
Rebased 🎉

**Pull request merged**
