### PR TITLE
Typescript declarations

### PR DESCRIPTION
**Pull request by ibratoev**
Typescript declarations make it much easier to consume the package with Typescript.
More info about how declaration should be published: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Tested internally on my project.
I can help with support in the future ;)

### CODE REVIEW

**Comment by SimenB** [comment]
Is it possible to have some tests as well? Pretty easy to break this without knowing (even with such a small API surface) 😄 

You don't by chance feel the call to add flow typings as well? 😀

**Comment by af** [comment]
Thanks @ibratoev ! I'll take these for a spin and read the link you provided tonight. As someone who is not familiar with TypeScript, I have the same question as @SimenB, is there any way to have a regression test for the typings so that it'll fail if the API changes without the typings keeping up?

**Comment by ibratoev** [comment]
I will see what kind of tests I can add. I can try using this: https://www.npmjs.com/package/typescript-definition-tester

About *flow*, I don't use it. Maybe people can use this to convert the typings if needed: https://github.com/joarwilk/flowgen

**Comment by ibratoev** [comment]
And, btw, give TypeScript a shot ;) It is a very well managed project and it can help a ton for larger apps.

**Comment by af** [comment]
@ibratoev First off, apologies for the noob Typescript questions :). I tried changing `examples/env.js` to `env.ts` and then compiling with `tsc` (which I just installed globally). I had to install `@types/node` as a dev dependency to get it to compile, and then it works. However, once I try doing something that violates the types (eg. passing `{strict: 123}` as a 3rd arg to `cleanEnv()`, it still compiles fine. Any ideas how I can get it to verify that the types catch errors as expected? I understand that I might be doing things completely wrong :P

**Comment by ibratoev** [comment]
@af, just pushed tests and improvements. The easiest way to verify it is to check out the `envalid.ts` test file, modify it and run the tests ;)

In you example, most probably the issue is that you have to use `import` instead of `require`. The Typescript `import` is almost the same as the ES6 import. More info: https://www.typescriptlang.org/docs/handbook/modules.html#import 
In your particular example it should be:
```
import * as envalid from '..'
```

**Comment by af** [comment]
Thanks @ibratoev, this looks good. Oh and changing the require() to an import statement did fix my test with the example btw.

**Comment by kachkaev** [comment]
@ibratoev I've began to use envalid's TypeScript definitions in a new project and they really help! The only thing I haven't managed to get is an error when I mistype a name of an env variable. Here's the example:

```ts
// env.ts
import * as envalid from "envalid";

export default envalid.cleanEnv(process.env, {
  TEST: envalid.str(),
});
```

```ts
// index.ts
import env from "./env";

console.log(env.TEST); // ✅ autocompletion works, ✅ OK for TS 
console.log(env.WRONG_VAR); // ✅ autocompletion does not work, 🚫 still OK for TS
```

I suspect that TypeScript is powerful enough to generate an error for `env.WRONG_VAR`, but I'm not quite sure how to do so. What are your thoughts on this?

**Pull request merged**
