### PR TITLE
Add type information to exported objects

### PR DESCRIPTION
**Pull request by SimenB**
We have a small wrapper for this module pretty printing available config to the console. Including the type information in that would be great!

### CODE REVIEW

**Comment by af** [comment]
Thanks for the feature suggestion and PR! Could you show me an example of how you use/consume this extra type information? I'd like to understand the use case a little more before merging.

**Comment by SimenB** [comment]
Sure!
We've gone for a pattern where you have a directory, exporting a bunch of objects that are using envalid, e.g.:

```js
// dir/fileA.js
'use strict';

const { bool, str } = require('envalid');

module.exports = {
    SOME_ENV: str({
        desc: 'some awesome description',
        default: 'default value'
    }),
    SOMETHING_ELSE: bool({
        desc: 'this is true, I swear',
        devDefault: false,
    })
```

```js
// dir/fileB.js
'use strict';

const { str } = require('envalid');

module.exports = {
    SOMETHING_ELSE_ENTIRELY: str({
        desc: 'some really, really awesome description',
    })
```

You then pass the path of this directory into our module, which loads every single config and flattens it.

This single object can then be passed to `cleanEnv` in order for it to do its magic.

But something else we do with this object, is that we have a script which loads the same object, but all it does is pretty print it to the console, printing the name, description and defaults (if they exist) like this (some massaging of the data has happened before this):

```js
function prettyPrintSchemaItem ([name, opts]) {
    const { desc = 'not set', devDefault = 'not set', choices } = opts;
    // can't destructure reserved words with defaults :(
    const theDefault = opts.default === undefined ? 'not set' : opts.default;
    console.log(`  ${name} - ${desc}`);
    console.log(`    default: ${theDefault}`);
    console.log(`    devDefault: ${devDefault}`);
    if (choices) {
        console.log(`    choices: ${choices.join(', ')}`);
    }
}
```

The use case for this is to allow devs to easily print every single config option they can pass from the command line, by simply running `npm run show-config`.

**Comment by SimenB** [comment]
Oh, this PR allows us to add type information in addition the what we currently print 😄

**Comment by SimenB** [comment]
I can see I also forgot to update the README, I'll get to it

**Comment by SimenB** [comment]
@af Done, should be GTG now

**Comment by af** [comment]
Thanks, I'm away today but I'll try and take a closer look tomorrow

**Comment by af** [comment]
I had actually wanted to add something similar to the default reporter a few months ago but completely forgot about it :) So I may later tweak this slightly in order to support that feature, but the extra arg to `makeValidator()` and `validator.type` should stay the same

**Comment by SimenB** [comment]
Similar to the printing? Or requiring and flattening dirs? 
We also add a proxy around it, so it throws if you try to access a non-existent prop. 
I'm sure we could open source our tool, if you're interested

**Comment by SimenB** [comment]
Could you release this, btw?

**Comment by af** [comment]
I just published v2.3.0 with the results of this PR. The feature I wanted to add to the reporter was the type information– so if you forgot to set a required var, the reporter told you its type as well as its name. I'll have to rework how exceptions are thrown and handled to add this though.

**Comment by SimenB** [comment]
Ah, cool!

**Pull request merged**
