### PR TITLE
docs: Add logo

### PR DESCRIPTION
**Pull request by cobraz**
Hello 👋

Thank you again for this awesome package. I had some fun playing around with a _logo_ for `envalid`, so I thought I'd listen in on what you/people think about it. Maybe it could be used for `envalid`?

Couldn't make up my mind if it should be centred or aligned left, so I'm opening up two pull requests. This one has the header centred, but #163 has it aligned left.

See the preview here: https://github.com/cobraz/envalid/tree/add-center-header

### CODE REVIEW

**Comment by af** [comment]
This is nice, thanks! I really like the centered layout, it never occurred me to apply any design sense to the readme :D 

Could you just reduce the vertical height (padding) around the logo? It takes up a little too much space for my taste currently. Otherwise LGTM

**Comment by AnneMatilde** [comment]
Centered layout looks best to me too. Have you thought about how it will look on dark mode? Maybe you could test out a bright color on the bakcground or on the outline of the text?

**Comment by cobraz** [comment]
> Could you just reduce the vertical height (padding) around the logo? It takes up a little too much space for my taste currently. Otherwise LGTM

I looks kind of weird if we just squeeze the box:

Skjermbilde 2021-08-08 kl  12 26 43

So maybe change the form of it to a square box (with some rounded corners)?

Skjermbilde 2021-08-08 kl  12 26 06

Or maybe better, remove the box altogether? What do you think, @AnneMatilde ?

Skjermbilde 2021-08-08 kl  12 24 34

**Comment by cobraz** [comment]
@af should we land this? :)

**Comment by cobraz** [comment]
Updated with the third suggestion, see the preview here: 
https://github.com/cobraz/envalid/tree/add-center-header

**Comment by af** [comment]
Merged, thanks for revisiting this 👍

**Pull request merged**
