### PR TITLE
Added 'Symbol(nodejs.util.inspect.custom)' to inspect symbols

### PR DESCRIPTION
**Pull request by witq**
I'm not sure in which version of node this changed, but I was encountering issues on 10.15.1.

### CODE REVIEW

**Comment by SimenB** [comment]
ind taking a look at CI?

**Comment by witq** [comment]
I thought I was going to be smart and edited the file inline on github and inadvertently skipped pre-commit and pre-push checks. Then had to move the inspectables and inspectSymbolStrings out of the  get method because code climate was complaining about the number of lines (26 versus the desired 25). All should be good now 👍

**Comment by SimenB** [comment]
@af might be worth a patch 🙂

**Comment by af** [comment]
v4.2.2 published!

**Pull request merged**
