### PR TITLE
Add Array validator

### PR DESCRIPTION
**Pull request by johman10**
Hi there!
Thanks for the package, great work and very easy to build upon! :+1:

Personally I missed an Array type, so I added one.
When used it should normalise an comma separated string with or without spaces and return an array with strings.

This is not really related to any issue, just figured this would be a good addition to all the other validators there already is.

### CODE REVIEW

**Comment by af** [comment]
Hi, thanks for the PR! What does this new validator do that the json one can't? eg: ```
    cleanEnv({ FOO: '[1,3,4]' }, { FOO: json() })
```

**Comment by SimenB** [comment]
Being +0 on the validator, it guarantees input is an array, as opposed to something's json parsable

**Comment by johman10** [comment]
@af has a good point. I think the main difference is that this would allow: `'test, 1, 123'` as well, so brackets aren't forced upon the user. The downside is that the current implementation doesn't `parseInt`, as `JSON.parse` would.

Maybe, I can improve upon this. Validate that the send in string is in an array-like format (e.g. no key value, comma separated etc). And then call `JSON.parse` on it. What do you think about that @af?

**Comment by af** [comment]
Hi @johman10, sorry for the delay in getting back to you. Since we want to keep the built-in validator options lean, and there's so much overlap with the existing JSON validator, I'm not in favour of adding this as-is. Maybe we could find a way to split `json()` into `jsonObj()` and `jsonArray()` instead?

Of course, you can still use the array validator in your project(s) as a [custom validator](https://github.com/af/envalid#custom-validators)

**Comment by ilkka** [comment]
While it's easy enough to add a custom validator for this, it seems to me like there is a slight problem with how `default` works in that case.

```typescript
const stringArrayValidator = makeValidator<string[]>((input: string) => ... )
```

A validator that validates an env var as having e.g. type `string[]` will take a spec where the type of `default` is of course also `string[]`. This default will also be passed into the parser function given to `makeValidator`. Okay, so the parser function needs to first check if `input` is actually an array already, and if it is, skip calling e.g. `input.split(",")`. The TypeScript types however claims that it is a `string`.

I guess the simple (in terms of the API) fix would be to make the type work something like

```typescript
function makeValidator<A>(parser: (input: string | A) => any, type?: string | undefined): ...
```

Then one would be forced to handle the case where the input to the parser is the default value.

**Comment by ilkka** [comment]
I realised I can just type the parser myself like my second example, because of course it is valid to assign a `(input: A | B) => C` to `(input: A) => C`. I didn't think to even try that, since what I saw in the typings was unambiguously just `string` 🤷‍♂

**Pull request closed without merging**
